### ISSUE TITLE
🚑️ Marten Timeout causes all Budget pages to not work

### ISSUE THREAD

**Issue by Hona** [Hona/UpBlazor#31]
Error Message:

```
System.TimeoutException: The operation has timed out.
   at Marten.Util.TimedLock.Lock(TimeSpan timeout)
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature, CancellationToken token)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Marten.Storage.Tenant.EnsureStorageExists(Type featureType)
   at Marten.Internal.StorageCheckingProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor(Type documentType)
   at Marten.Linq.Parsing.LinqHandlerBuilder..ctor(MartenLinqQueryProvider provider, IMartenSession session, Expression expression, ResultOperatorBase additionalOperator, Boolean forCompiled)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token)
   at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.ToListAsync[T](IQueryable`1 queryable, CancellationToken token)
   at UpBlazor.Infrastructure.Repositories.IncomeRepository.GetAllByUserIdAsync(String userId) in /src/src/UpBlazor.Infrastructure/Repositories/IncomeRepository.cs:line 27
   at UpBlazor.Web.Shared.Components.RepositoryWrapper`2.OnParametersSetAsync() in /src/src/UpBlazor.Web/Shared/Components/RepositoryWrapper.razor:line 58
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by Hona** [comment]
Fixed because of docker-compose's networking added:

```
links
    - db
```
