### ISSUE TITLE
[Bug] When changing forecast get 500 error

### ISSUE THREAD

**Issue by thesammykins** [Hona/UpBlazor#50]
When you adjust the slider and press load, you get a 500 error. This seems to occur on any number under 340 days, it doesn't effect going beyond 365 days.

```
> Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
>       HTTP Response: 
>       
>       {"title":"An unexpected error occurred.","status":500}
>       
>       UpBlazor.ApiClient.ApiException: The HTTP status code of the response was not expected (500).
>       
>       Status: 500
>       Response: 
>       {"title":"An unexpected error occurred.","status":500}
>          at UpBlazor.ApiClient.ForecastClient.GetExpenseForecastAsync(Nullable`1 totalDays, CancellationToken cancellationToken)
>          at UpBlazor.WebUI.Pages.Insights.Forecast.Index.ReloadAsync()
>          at UpBlazor.WebUI.Pages.Insights.Forecast.Index.HandleLoadClick()
>          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>          at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
>          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
> HTTP Response: 
> 
> {"title":"An unexpected error occurred.","status":500}
> 
> UpBlazor.ApiClient.ApiException: The HTTP status code of the response was not expected (500).
> 
> Status: 500
> Response: 
> {"title":"An unexpected error occurred.","status":500}
>    at UpBlazor.ApiClient.ForecastClient.GetExpenseForecastAsync(Nullable`1 totalDays, CancellationToken cancellationToken)
>    at UpBlazor.WebUI.Pages.Insights.Forecast.Index.ReloadAsync()
>    at UpBlazor.WebUI.Pages.Insights.Forecast.Index.HandleLoadClick()
>    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>    at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
>    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by Hona** [comment]
This should be fixed now - please test and close if you're happy :)

**Comment by thesammykins** [comment]
Perfect :D Thanks for fixing all these btw, makes finding out if I'm currently screwing myself over financially haha.

**Comment by Hona** [comment]
Haha all good, that is exactly why I made it.

Am I wasting all my money? 
If I wasn't an idiot, how much could I save in 6 months, etc.

Its crazy how much you can save if you're disciplined but its hard
